Initial project structure
PWrInSpace/MACKI_solenoids_board pull request #1
Opened 2024-02-22 20:41 UTC by JSiuda1

2024-02-22 23:23 UTC, kgliwinski approved these changes
Review changes before merging 🙏 🐕

2024-02-22 23:23 UTC, kgliwinski commented on .clang-format
To add:
InsertNewlineAtEOF: true **(this is must have - limts lint issues, but doesn't eliminate them)**
BreakBeforeBraces: Attach
InsertBraces: true

2024-02-22 23:23 UTC, kgliwinski commented on .github/workflows/gitci.yml
Nice to have if tests are planned:
```yml
on: push

jobs:
  build_ESP32:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: esp-idf build
      uses: espressif/esp-idf-ci-action@v1
      with: 
        esp_idf_version: release-v5.1
        target: 'esp32s3'
        path: 'Mainboard_ESP32'
        
  build_ESP32_tests:
      
      runs-on: ubuntu-latest
  
      steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: esp-idf build
        uses: espressif/esp-idf-ci-action@v1
        with: 
          esp_idf_version: release-v5.1
          target: 'esp32s3'
          path: 'Mainboard_ESP32/test'

  lint:
    runs-on: ubuntu-latest


    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install cpplint
    - name: run lint
      run: bash lint.sh
```

2024-02-22 23:23 UTC, kgliwinski commented on .clang-format
The rest of these are optional

2024-02-23 23:13 UTC, JSiuda1 commented on .clang-format
G

2024-02-23 23:16 UTC, JSiuda1 commented on .github/workflows/gitci.yml
Cpplint and cppcheck have been configured :nerd_face:

2024-02-23 23:41 UTC, kgliwinski requested changes

2024-02-23 23:41 UTC, kgliwinski commented on CPPLINT.cfg
> +linelength=80
ColumnLimit in clang-format set to 100, either change this to 100 or ColumnLimit to 80

2024-02-24 15:45 UTC, kgliwinski approved these changes
Essa

2024-02-24 18:02 UTC, merged